AWSTemplateFormatVersion: "2010-09-09"
Description: Main stack to deploy all sub-modules (VPC, NAT Gateway, EC2 Instances)

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-modules/vpc-networking.yml
      Parameters:
        VPCName: Lab1_Group9
        VPCCIDR: 10.0.0.0/16
        PublicSubnetCIDR: 10.0.0.0/24
        PrivateSubnetCIDR: 10.0.1.0/24

  NATGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-modules/nat-gateway.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet0
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnet0

  EC2InstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-modules/ec2-instances.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet0
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnet0
        KeyName: Lab1_Group9_Key
        InstanceTypeParameter: t3.micro
        PublicEC2InstanceSecurityGroupId: !GetAtt SecurityGroupStack.Outputs.PublicEC2InstanceSecurityGroup
        PrivateEC2InstanceSecurityGroupId: !GetAtt SecurityGroupStack.Outputs.PrivateEC2InstanceSecurityGroup
        PublicEC2InstanceName: Lab1_Group9_Public_EC2_Instance
        PrivateEC2InstanceName: Lab1_Group9_Private_EC2_Instance
      
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-modules/security-group.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId

  RouteTablesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-modules/route-tables.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        InternetGateWayName: Lab1_Group9_IGW
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet0
        NetworkAclName: Lab1_Group9-public-nacl

Outputs:
  VPCId:
    Description: VPC ID of the VPC created
    Value: !GetAtt VPCStack.Outputs.VPCId

  PublicSubnetId:
    Description: Subnet ID of the public subnet
    Value: !GetAtt VPCStack.Outputs.PublicSubnet0

  PrivateSubnetId:
    Description: Subnet ID of the private subnet
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet0

  PublicEC2InstanceSecurityGroupId:
    Description: Security Group ID of Public EC2 Instance
    Value: !GetAtt SecurityGroupStack.Outputs.PublicEC2InstanceSecurityGroup

  PrivateEC2InstanceSecurityGroupId:
    Description: Security Group ID of Private EC2 Instance
    Value: !GetAtt SecurityGroupStack.Outputs.PrivateEC2InstanceSecurityGroup